
package com.labwing.s3ft;

import com.jfixby.scarabei.api.collections.Collections;
import com.jfixby.scarabei.api.collections.List;
import com.jfixby.scarabei.api.file.File;
import com.jfixby.scarabei.api.file.LocalFileSystem;
import com.jfixby.scarabei.api.strings.Strings;

public class LabWingCloud {

	public static List<String> listIgnoredFiles () {
		return Collections.newList(".git", ".gitignore", ".idea");
	}

	public static List<String> listIgnoredExtentions () {
		final String gitignore = LabWingCloud.gitIgnoreRaw();

		final List<String> split = Strings.split(gitignore, "\r\n");

		final List<String> resilt = Collections.newList();
		Collections.convertCollection(split, resilt, s -> {
			int beginIndex = s.indexOf("*.");
			if (beginIndex == -1) {
				return s;
			}
			beginIndex = beginIndex + "*.".length();
			return s.substring(beginIndex);
		});

		return resilt;
	}

	public static String gitIgnoreRaw () {
		final String gitignore = "*.idea\r\n" + //
			"*.dll\r\n" + //
			"*.png\r\n" + //
			"*.exe\r\n" + //
			"*.pdb\r\n" + //
			"*.pbix\r\n" + //
			"*.rdl\r\n" + //
			"*.gif\r\n" + //
			"*.jpg\r\n" + //
			"*.jpeg\r\n" + //
			"*.swf\r\n" + //
			"*.xml\r\n" + //
			"*.svg\r\n" + //
			"*.cache\r\n" + //
			"";
		return gitignore;
	}

	public static List<String> listIncludedExtentions () {
		return Collections.newList(//
			"cs", //
			"vb", //
			"aspx"//
		);
	}

	public static List<File> listAutogeneratedFiles () {
		final String list = "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.Crm.Dynamics\\Domain\\LabWingSdkTypes.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.Crm.Dynamics\\Domain\\Utility\\OptionSets.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabCarrier.WingControl\\Webserver\\Cassini.Gui\\Properties\\Resources.Designer.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabCarrier.WingControl\\Webserver\\Cassini.Gui\\Properties\\Settings.Designer.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.Middleware.CSH\\obj\\Debug\\net452\\LabsOfTime.Middleware.CSH.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LabApp\\LabApp3.0\\API\\Connected Services\\LabWingWebService\\Reference.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LabApp\\LabApp3.0\\LabApp\\LabApp.Android\\Resources\\Resource.designer.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LogisticsHub\\LabsOfTime.LogisticsHub.Core\\obj\\Debug\\net452\\LabsOfTime.LogisticsHub.Core.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LogisticsHub\\LabsOfTime.LogisticsHub.Core\\obj\\Debug\\net48\\LabsOfTime.LogisticsHub.Core.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LogisticsHub\\LabsOfTime.LogisticsHub.CSHTest\\obj\\Debug\\net472\\LabsOfTime.LogisticsHub.CSHTest.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LogisticsHub\\LabsOfTime.LogisticsHub.Data\\obj\\Debug\\net452\\LabsOfTime.LogisticsHub.Data.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LogisticsHub\\LabsOfTime.LogisticsHub.Data\\obj\\Debug\\net472\\LabsOfTime.LogisticsHub.Data.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LogisticsHub\\LabsOfTime.LogisticsHub.Data\\obj\\Debug\\net48\\LabsOfTime.LogisticsHub.Data.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LabApp\\LabApp3.0\\API\\obj\\Debug\\netstandard2.0\\LabsOfTime.LabApp.API.AssemblyInfo.cs\r\n"
			+ "D:\\LabWing\\Labs-of-Time\\Labs-of-Time\\LabsOfTime.LabApp\\LabApp3.0\\API\\obj\\Release\\netstandard2.0\\LabsOfTime.LabApp.API.AssemblyInfo.cs\r\n"
			+ "";
		final List<String> l = Strings.split(list.replaceAll("\\\\", "/"), "\\r\\n");
		final List<File> f = Collections.newList();
		Collections.convertCollection(l, f, path -> LocalFileSystem.newFile(path));
// L.d("f", f);
// Sys.exit();
		return f;
	}

}
