
package com.labwing.s3ft;

import java.io.IOException;

import com.jfixby.scarabei.api.collections.Collections;
import com.jfixby.scarabei.api.collections.List;
import com.jfixby.scarabei.api.file.File;
import com.jfixby.scarabei.api.file.FilesList;
import com.jfixby.scarabei.api.file.LocalFileSystem;
import com.jfixby.scarabei.api.log.L;
import com.jfixby.scarabei.api.strings.Strings;
import com.jfixby.scarabei.api.sys.settings.ExecutionMode;
import com.jfixby.scarabei.api.sys.settings.SystemSettings;
import com.jfixby.scarabei.red.desktop.ScarabeiDesktop;

public class ScanForTooBig {

	public static void main (final String[] args) throws IOException {
		ScarabeiDesktop.deploy();
		SystemSettings.setExecutionMode(ExecutionMode.PUBLIC_RELEASE);

		final List<String> alreadyIgnored = alreadyIgnored();

		final File labsOfTime = LocalFileSystem.newFile("D:\\LabWing\\Labs-of-Time\\Labs-of-Time");
		final FilesList list = labsOfTime.listAllChildren(file -> {

			if (alreadyIgnored.contains(file.getExtension())) {
				return false;
			}

			try {
				if (file.getSize() > 128 * 1024) {
					final String path = file.toJavaFile().toString().replaceAll("\\\\", "/");
					final String prefilx = "D:/LabWing/Labs-of-Time/Labs-of-Time/";

					final String data = file.readToString();
					if (data.contains("<auto-generated>")) {
						return false;
					}

// path = path.substring(prefilx.length());
					L.d(path);
					return true;
				}
			} catch (final IOException e) {
				e.printStackTrace();
			}

			return false;
		});
// L.d("list", list);

	}

	private static List<String> alreadyIgnored () {
		final String gitignore = LabWingCloud.gitIgnoreRaw();

		final List<String> split = Strings.split(gitignore, "\r\n");

		final List<String> resilt = Collections.newList();
		Collections.convertCollection(split, resilt, s -> {
			int beginIndex = s.indexOf("*.");
			if (beginIndex == -1) {
				return s;
			}
			beginIndex = beginIndex + "*.".length();
			return s.substring(beginIndex);
		});

		return resilt;
	}

}
